name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '22'
    
    - name: Generate changelog
      id: changelog
      run: |
        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        # Calculate new version to use as target for release notes
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        if [ "${{ inputs.version_type }}" = "major" ]; then
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print ($1+1) "." 0 "." 0}')
        elif [ "${{ inputs.version_type }}" = "minor" ]; then
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." ($2+1) "." 0}')
        else # patch
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." $2 "." ($3+1)}')
        fi
        
        # Generate release notes using GitHub API
        if [ -z "$LATEST_TAG" ]; then
          # If no previous tag exists, generate notes from first commit
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          CHANGELOG=$(gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="v${NEW_VERSION}" \
            -f target_commitish="${{ github.sha }}" \
            -f previous_tag_name="" \
            --jq '.body')
        else
          CHANGELOG=$(gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="v${NEW_VERSION}" \
            -f target_commitish="${{ github.sha }}" \
            -f previous_tag_name="$LATEST_TAG" \
            --jq '.body')
        fi
        
        # Save changelog to environment
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        echo "NEW_VERSION_NUMBER=$NEW_VERSION" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update version files
      run: |
        # Update package.json version manually
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        if [ "${{ inputs.version_type }}" = "major" ]; then
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print ($1+1) "." 0 "." 0}')
        elif [ "${{ inputs.version_type }}" = "minor" ]; then
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." ($2+1) "." 0}')
        else # patch
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." $2 "." ($3+1)}')
        fi
        
        # Update package.json
        node -e "
          const pkg = require('./package.json');
          pkg.version = '$NEW_VERSION';
          require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');
        "
        
        # Update package-lock.json if it exists
        if [ -f "package-lock.json" ]; then
          node -e "
            const lockPkg = require('./package-lock.json');
            lockPkg.version = '$NEW_VERSION';
            if (lockPkg.packages && lockPkg.packages['']) {
              lockPkg.packages[''].version = '$NEW_VERSION';
            }
            require('fs').writeFileSync('./package-lock.json', JSON.stringify(lockPkg, null, 2) + '\n');
          "
        fi
        
        echo "NEW_VERSION=v$NEW_VERSION" >> $GITHUB_ENV
        echo "RELEASE_BRANCH=release/$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.RELEASE_BRANCH }}
        commit-message: "chore: bump version to ${{ env.NEW_VERSION }}"
        title: "Release ${{ env.NEW_VERSION }}"
        body: |
          # Release ${{ env.NEW_VERSION }}
          
          ${{ env.CHANGELOG }}
          
          ---
          
          **Release Type:** ${{ inputs.version_type }} update
          
          **Note:** This PR will trigger a release when merged to master.
        base: master
        labels: |
          Type: Release
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}