name: Merge Gatekeeper

on:
  pull_request:
    branches: [ master ]

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
    - uses: upsidr/merge-gatekeeper@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}