name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Release ')
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Run tests
      run: npm run test:unit
    
    - name: Create GitHub tag and release
      run: |
        # Get version from package.json
        VERSION="v$(node -p "require('./package.json').version")"
        
        # Create tag
        git tag $VERSION
        git push origin $VERSION
        
        # Create GitHub release with PR body as release notes
        gh release create $VERSION \
          --title "Release $VERSION" \
          --notes "${{ github.event.pull_request.body }}" \
          --latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and upload assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run dist