name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build application
      run: npm run build
    
    - name: Run tests
      run: npm run test:unit
    
    # macOS specific steps
    - name: Build and release (macOS)
      if: matrix.os == 'macos-latest'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run dist
    
    # Windows specific steps  
    - name: Build and release (Windows)
      if: matrix.os == 'windows-latest'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run dist
    
    # Linux specific steps
    - name: Build and release (Linux)
      if: matrix.os == 'ubuntu-latest'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run dist